### ISSUE TITLE
Object detail view improvement

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/manager#24]
In `Data / Objects / edit object` 

* [x] move `uname` down, just before `meta` - this field is usually not editable
* [ ] [minor] in `meta` -> `created_by` and `modified_by` displayed by username instead of id and internal link to user view
* [x] `extra` field now shows `[object Object]` when populated, display JSON editable content
* [ ] [minor] **ckeditor** icons for _bold_, _italic_, _link_ in toolbar are not visible

**Comment by edoardocavazza** [comment]
@stefanorosanelli @batopa @fquffio Is there a way to "include" hidden `created_by` and `modified_by` relationships when fetching an object?

**Comment by fquffio** [comment]
Not so far. We don't expose those as full-featured relationships since they are actually read-only, and they are updated every time an object is updated.

We might implement something similar to streams: add those keys in `relationships` dictionary, but return 403 every time somebody tries to `PATCH /objects/:id/relationships/created_by_user`. 🤔

**Comment by stefanorosanelli** [comment]
if problematic we can safely skip `meta.created_by/modified_by` point and do it later
I've marked it as `minor`
