### ISSUE TITLE
Update javascript build environment

### ISSUE THREAD

**Issue by xho** [bedita/manager#360]
Update at least Babel and Webpack to support the latest language features.

**Comment by edoardocavazza** [comment]
I would like to re-open this issue since yesterday the TC39 committee has moved optional chaining and null coalescing to stage 4. It means that those babel plugins will be very early enabled by default in the preset env.

Tracking issues:
https://github.com/babel/babel/issues/10809
https://github.com/babel/babel/issues/10810
https://github.com/babel/babel/issues/10813

**Comment by didoda** [comment]
@xho @edoardocavazza is this issue still necessary or could we close it?

**Comment by edoardocavazza** [comment]
We can close it.
